Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pudb-2016.2-py2.7.egg/pudb/__init__.py", line 77, in runscript
    dbg._runscript(mainpyfile)
  File "/usr/local/lib/python2.7/dist-packages/pudb-2016.2-py2.7.egg/pudb/debugger.py", line 419, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "Main.py", line 63, in <module>
    cell_handler.driver(5)
  File "Handler.py", line 160, in driver
    self.itertor(self.route_list[route_id])
  File "Handler.py", line 201, in itertor
    output_cars = self._update_cars(output_cars)
  File "Handler.py", line 38, in _update_cars
    for item in enumerateoutput_cars:
NameError: global name 'enumerateoutput_cars' is not defined
